version: '2'
services:

  iib-on-premise:
    build: 99_docker/iib-sc2/
    image: sg248351/iib-sc2
    depends_on:
      - mq
    ports:
      - "4414"
      - "7800"
    networks:
      sc2-net:
        aliases:
          - iib
    environment:
      - LICENSE=${LICENSE}

  mq:
    image: sg248351/eventqm
    ports:
      - "1414"
    networks:
      sc2-net:
        aliases:
          - mq
    environment:
      - LICENSE=${LICENSE}

networks:
  sc2-net:
    driver: bridge
