version: '2'
services:
  stub:
    build: 99_docker/stub/
    image: sg248351/order-api-stub
    depends_on:
      - mq
    ports:
      - "4414"
      - "7800"
    environment:
      - LICENSE=${LICENSE}
  mq:
    image: sg248351/eventqm
    ports:
      - "1414"
    environment:
      - LICENSE=${LICENSE}
