version: '2'
services:

  stub:
    build: 99_docker/stub/
    image: sg248351/order-api-stub
    depends_on:
      - mq
    ports:
      - "4414"
      - "7800"
    networks:
      sc2-net:
        aliases:
          - stub
    environment:
      - LICENSE=${LICENSE}

  mq:
    image: sg248351/eventqm
    ports:
      - "1414"
    networks:
      sc2-net:
        aliases:
          - mq
    environment:
      - LICENSE=${LICENSE}

  sgc:
    build: 99_docker/sgc/
    image: sg248351/secure-gateway-client
    depends_on:
      - stub
      - mq
    #command: [nq9qKFXqQq4_prod_ng, -F, /tmp/aclfile.txt, --sectoken, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25maWd1cmF0aW9uX2lkIjoibnE5cUtGWHFRcTRfcHJvZF9uZyIsInJlZ2lvbiI6InVzLXNvdXRoIiwiaWF0IjoxNDc0MDExNjk4LCJleHAiOjE0ODE3ODc2OTh9.mwS9FM4cks5m0ppfHqP7oR_cM9mGo-JHZ1N8UUujNkk]
    command: ["${SC2_GWID}", -F, /tmp/aclfile.txt, --sectoken, "${SC2_SECTOKEN}"]
    networks:
      sc2-net:
        aliases:
          - sgc

networks:
  sc2-net:
    driver: bridge
